#!/bin/sh

set -eu

# get a list of connected disks
disks=$(sysctl -a 'kern.geom.disk' | cut -d '.' -f4)

# print the serial and temperature for each disk
# this is the only part of the script that needs root
for i in $disks; do
	temp="$(smartctl -A /dev/"$i" | grep "Temperature_Celsius" | cut -w -f10)"
	serial="$(smartctl -i /dev/"$i" | grep "Serial Number" | cut -w -f3)"
	cat -t <<- _EOF_
		$(date +%s),$i,$serial,$temp
_EOF_
done

exit 0
